language: go

services:
  - mysql

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - mysql -uroot -e 'create database if not exists sqlxxtest;'
  - mysql -uroot -e 'create user if not exists sqlxxtester@localhost identified by "Passw0rd!";'
  - mysql -uroot -e 'grant all privileges on sqlxxtest.* to sqlxxtester@localhost;'
  - go get github.com/mattn/goveralls

script:
  - go test -cover -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
